#!/bin/sh




volume=$(echo 0$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}')"*100" | bc | sed "s/\([0-9]\)\..*/\1/")
muted=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}')
icon=""
if [ "$muted" = "[MUTED]" ]; then
    icon="󰝟"
    echo "$icon"
    exit
elif [ "$volume" -le 0 ]; then
    icon="󰸈"
elif [ "$volume" -le 33 ]; then
    icon="󰕿"
elif [ "$volume" -le 66 ]; then
    icon="󰖀"
elif [ "$volume" -le 100 ]; then
    icon="󰕾"
fi
echo "$icon" "^c#7da6ff^^b#19181a^ $volume""%"
