#!/bin/sh

set -e

pow=$(cat /sys/class/power_supply/*/capacity)
status=$(cat /sys/class/power_supply/*/status)
icon="󰂃"

unknown="󰂃"

charging()
{
    if [ "$pow" -le 10 ]; then
        icon="󰢜"
    elif [ "$pow" -le 20 ]; then
        icon="󰂆"
    elif [ "$pow" -le 30 ]; then
        icon="󰂇"
    elif [ "$pow" -le 40 ]; then
        icon="󰂈"
    elif [ "$pow" -le 50 ]; then
        icon="󰢝"
    elif [ "$pow" -le 60 ]; then
        icon="󰂉"
    elif [ "$pow" -le 70 ]; then
        icon="󰢞"
    elif [ "$pow" -le 80 ]; then
        icon="󰂊"
    elif [ "$pow" -le 90 ]; then
        icon="󰂋"
    elif [ "$pow" -le 100 ]; then
        icon="󰂅"
    fi
}

discharging()
{
    if [ "$pow" -le 10 ]; then
        icon="󰁺"
    elif [ "$pow" -le 20 ]; then
        icon="󰁻"
    elif [ "$pow" -le 30 ]; then
        icon="󰁼"
    elif [ "$pow" -le 40 ]; then
        icon="󰁽"
    elif [ "$pow" -le 50 ]; then
        icon="󰁾"
    elif [ "$pow" -le 60 ]; then
        icon="󰁿"
    elif [ "$pow" -le 70 ]; then
        icon="󰂀"
    elif [ "$pow" -le 80 ]; then
        icon="󰂁"
    elif [ "$pow" -le 90 ]; then
        icon="󰂂"
    elif [ "$pow" -le 100 ]; then
        icon="󰁹"
    fi
}

case "$status" in
    "Charging") charging
    ;;
    "Discharging") discharging
    ;;
    *) icon="$unknown"
    ;;
esac



echo "$icon" "^c#b9f27c^^b#19181a^ $pow""%%"
