#!/bin/sh



bright=$(cat /sys/class/backlight/*/brightness)
maxbright=$(cat /sys/class/backlight/*/max_brightness)
percent=$(((bright * 100) / maxbright))
symbol=""
if [ "$percent" -lt 15 ]; then
    symbol="󰃜"
elif [ "$percent" -lt 29 ]; then
    symbol="󰃛"
elif [ "$percent" -lt 43 ]; then
    symbol="󰃚"
elif [ "$percent" -lt 57 ]; then
    symbol="󰃞"
elif [ "$percent" -lt 71 ]; then
    symbol="󰃟"
elif [ "$percent" -lt 85 ]; then
    symbol="󰃝"
elif [ "$percent" -le 100 ]; then
    symbol="󰃠"
fi

echo "$symbol " "^c#f7768e^^b#19181a^ $percent" "%"
